# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aKXeerp14aT0z-gFYql-JON1XFSzYqe
"""

# Verification Email: 24f2000846@ds.study.iitm.ac.in

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import IntSlider, interact, widgets
from IPython.display import display, Markdown

# Cell 1: Setup data and basic variables
# Generate x-values and base sine wave
x = np.linspace(0, 10, 100)

# Cell 2: Function to plot sine wave based on frequency (linked to slider)
def plot_sine(frequency=1):
    y = np.sin(frequency * x)
    plt.figure(figsize=(8, 4))
    plt.plot(x, y)
    plt.title(f'Sine Wave with Frequency = {frequency}')
    plt.xlabel('x')
    plt.ylabel('sin(frequency * x)')
    plt.grid(True)
    plt.show()

# Cell 3: Dynamic markdown text based on slider state
def update_text(frequency=1):
    return Markdown(f"### The sine wave frequency is currently set to **{frequency}**.")

# Cell 4: Create the interactive slider
freq_slider = IntSlider(min=1, max=10, value=1, description='Frequency:')

# Cell 5: Link slider with plot and markdown output
interactive_plot = widgets.interactive_output(plot_sine, {'frequency': freq_slider})
interactive_text = widgets.interactive(update_text, frequency=freq_slider)

# Display slider, plot, and dynamic text together
display(freq_slider, interactive_plot, interactive_text)