# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aKXeerp14aT0z-gFYql-JON1XFSzYqe
"""

# Verification Email: 24f2000846@ds.study.iitm.ac.in

# Cell 1: Data Setup
# This cell defines the dataset and variable used.
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import IntSlider, interact
import ipywidgets as widgets

# Generate a simple dataset
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Cell 2: Interactive plot with slider controlling frequency
# The slider value updates the frequency of the sine wave
def plot_sine(frequency=1):
    plt.figure(figsize=(8, 4))
    plt.plot(x, np.sin(frequency * x))
    plt.title(f'Sine Wave with Frequency = {frequency}')
    plt.xlabel('x')
    plt.ylabel('sin(frequency * x)')
    plt.grid(True)
    plt.show()

# Interactive slider widget controlling the frequency parameter
freq_slider = IntSlider(min=1, max=10, value=1, description='Frequency:')

# Cell 3: Dynamic markdown output that changes based on slider
def dynamic_text(frequency=1):
    return f"### The sine wave frequency is currently set to **{frequency}**."

# Using interact to connect slider to output functions
interactive_output = widgets.interactive_output(plot_sine, {'frequency': freq_slider})
markdown_output = widgets.interactive(dynamic_text, frequency=freq_slider)

# Display widgets and outputs
display(freq_slider, interactive_output, markdown_output)